Try to add `/std:c++latest` on Windows.
Otherwise;
```
D:\a\fasm\fasm\src\ParseFasm.cpp(296,29): error C7555: use of designated initializers requires at least '/std:c++latest' [D:\a\fasm\fasm\build\temp.win-amd64-3.6\Release\parse_fasm_tests.vcxproj]
```

Signed-off-by: Tim 'mithro' Ansell <me@mith.ro>